### ISSUE TITLE
分享失败

### ISSUE THREAD

**Issue by liuzoom** [shad0w-walker233/BaiduYun_Share#1]
Ubuntu16.04

{u'error_code': 31066, u'error_msg': u'file does not exist', u'request_id': 1995450273605376755}
Error: sharing file: /*/*/, errno: 31066, error_msg: file does not exist

不知道什么情况，但是使用bypy同步是可以的。

**Comment by sdwalker233** [comment]
你这里的'/'是相对地址吧，我之前使用了绝对地址，bypy的话是用'/app/bypy'的相对地址的。

已修复，现在相对地址会转换为绝对地址。
Thanks

**Comment by liuzoom** [comment]
可以了 是我搞错了，没仔细看文档，默认的他是分享已经上传过的文件。
我还以为是可以上传及分享同步进行呢。
多谢！
